controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    brake_release_controller:
      type: forward_command_controller/ForwardCommandController

diff_drive_controller:
  ros__parameters:
    left_wheel_names:
      - base_front_left_wheel_joint
      - base_middle_left_wheel_joint
      - base_back_left_wheel_joint
    right_wheel_names:
      - base_front_right_wheel_joint
      - base_middle_right_wheel_joint
      - base_back_right_wheel_joint

    # Physical left/right wheel-center separation from the URDF:
    # base_width (0.645 m) + wheel_length (0.05 m).
    wheel_separation: 0.695
    wheel_radius: 0.1
    wheel_separation_multiplier: 4.7
    wheel_radius_multiplier: 1.0
    
    
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

    pose_covariance_diagonal: [0.10, 0.10, 1000000.0, 1000000.0, 1000000.0, 1.0]
    twist_covariance_diagonal: [0.02, 10.0, 1000000.0, 1000000.0, 1000000.0, 1.0]

    enable_odom_tf: false
    publish_rate: 100.0

    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.75
    linear.x.min_velocity: -0.75
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 0.5
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 0.25
    angular.z.min_velocity: -0.25
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 0.9

    position_feedback: false
    open_loop: false
    use_stamped_vel: true

brake_release_controller:
  ros__parameters:
    joints:
      - base_front_left_wheel_joint
      - base_front_right_wheel_joint
      - base_middle_left_wheel_joint
      - base_middle_right_wheel_joint
      - base_back_left_wheel_joint
      - base_back_right_wheel_joint
    interface_name: reset_fault
